# -----------------------------
# S3 CSV file location
# -----------------------------
s3:
  bucket: "vadivel-data-engineer"     # your bucket name
  key: "my-company-list/my-company-list.csv"  # path to CSV inside bucket

# -----------------------------
# RDS Configuration
# -----------------------------
rds:
  user: "your_rds_username"       # default username if env var not set
  password: "your_rds_password"   # default password if env var not set
  host: "your_rds_endpoint"       # default endpoint if env var not set
  port: 3306
  database: "your_database_name"