name: Run PySpark ETL

on:
  workflow_dispatch:

jobs:
  emr-etl:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EMR_APP_ID: ${{ secrets.EMR_APP_ID }}
      EMR_EXEC_ROLE_ARN: ${{ secrets.EMR_EXEC_ROLE_ARN }}
      SCRIPT_URL: https://github.com/vayalaivadivel/etl-python-samples/tree/main/emr-etl-project/etl/conf/etl/src/load_s3_to_rds.py
      CONFIG_URL: https://github.com/vayalaivadivel/etl-python-samples/tree/main/emr-etl-project/etl/conf/config.yaml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Submit PySpark job to EMR Serverless
      run: |
        aws emr-serverless start-job-run \
          --application-id $EMR_APP_ID \
          --execution-role-arn $EMR_EXEC_ROLE_ARN \
          --release-label emr-6.16.0 \
          --job-driver '{
            "sparkSubmit": {
              "entryPoint": "'"$SCRIPT_URL"'",
              "entryPointArguments": ["'"$CONFIG_URL"'"],
              "sparkSubmitParameters": "--conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem"
            }
          }' \
          --region $AWS_REGION